import type { Metadata } from "next";
import { Playfair_Display, Inter } from "next/font/google";
import "../globals.css";
import { TopLoader as NextTopLoader } from "next-top-loader";
import { AdminLayoutClient } from "@/components/admin/admin-layout-client";

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"], // you can add more subsets if needed
  weight: ["400", "700"], // optional, define the weights you need
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"], // add more if needed
  weight: ["400", "500", "600", "700"], // optional: define the weights you need
});

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${playfairDisplay.variable} ${inter.variable} antialiased`}
      >
        <NextTopLoader color="var(--loader-color)" />
        <AdminLayoutClient>{children}</AdminLayoutClient>
      </body>
    </html>
  );
}
